resources:
- manager.yaml
- metrics_service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
- name: quay.io/openshift-pipeline/tekton-kueue
  newTag: v0.1.0
